package models

import (
	"encoding/json"
	"fmt"
	//"html/template"
	"github.com/joybynature/jbnserverapp/util"
	"github.com/kataras/iris"
	//	"github.com/kataras/go-template/html"

)

func TermOfServices(c *iris.Context) {
	//	c.MustRender("termsofservices.html", nil)
	termservice := `<html>
<body>
<main class="main-content container" role="main">

<div class="rte">
  <p><strong>GENERAL</strong></p>
<p><strong>In terms of Information Technology&nbsp;statutes, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.</strong> <br> <strong>This document is published in accordance with the provisions of Information Technology regulations that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of:</strong></p>
<ol>
<ol>
<li>The website www.joybynature.com (hereinafter referred to as <strong>‘Website’</strong>) and the IOS/Android application ‘Joybynature<strong>’</strong> (hereinafter referred to as <strong>"Application"</strong> or <strong>“App”</strong>),&nbsp;owned by Pavitra Retail Pvt. Ltd., a Company incorporated under the&nbsp; Companies Act, having its registered office at 43 Katwaria Sarai, New Delhi - 110016, India. Represented by its members, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns;</li>
<li>For the purpose of these Terms of Use, along with any amendments to the same, and wherever the context so requires<strong> "You"</strong> or&nbsp;<strong>"User"</strong> shall mean any natural or legal person who has agreed to become a user of the Application by installing the Application. The Application also provides certain services without registration/acceptance, and such provision of services does not absolve You of this contractual relationship. The term <strong>"We"</strong>,<strong> "Us"</strong>,<strong> "Our", ‘Company’</strong> shall mean Pavitra Retail Pvt. Ltd.;<strong> <strong>“Agreement” shall mean and refer to this Terms of Service, including any amendments that may be incorporated into it. “Third Party” shall mean and refer to any individual(s), company or entity apart from the User and </strong></strong>the Company.</li>
</ol>
</ol>
<p>The headings of each section in this Agreement are only for the purpose of organising the various provisions under this Agreement in an orderly manner. These headings shall not be used by either party to interpret the provisions contained under them in any manner. Further, the headings have no legal or contractual value.</p>
<ol>
<ol>
<li>By using the Website and App, You accept and agree to be bound by this Agreement, the&nbsp;Privacy Policy, as well as rules, guidelines, policies, terms, and conditions applicable to any service that is provided by this Application, that shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use.</li>
</ol>
</ol>
<p>Your use of Our Application is evidence that You have read and agreed to be contractually bound by these Terms of Service and our Privacy Policy. Please read both carefully. The use of this Website and Application by You is governed by this policy and any policy so mentioned by terms of reference.<br> If you do not agree with any of these terms, please discontinue using the Website and Application.</p>
<ol>
<ol>
<li>We hold the sole right to modify the Terms of Service without prior permission from You or providing notice to You. The relationship creates on You a duty to periodically check the Terms of Service and stay updated on its requirements. If You continue to use the Website and Application or avail any of its services without registration following such change, this is deemed as consent by You to the so amended policies. Your continued use of the Website and Application is conditioned upon your compliance with the Terms of Service, including but not limited to compliance with the Terms of Service even after alterations, if any.</li>
</ol>
</ol>
<p><strong>ONLINE PLATFORM</strong></p>
<p>The Website/App is an online platform through which We help Users achieve wellbeing goals through Content, Community and Sale of Organic and Natural products. We are the largest player in the online sale of Natural and Organic products, and support both nationwide and international delivery. Users can purchase Our products from the Website after registration.</p>
<p><strong>MEMBERSHIP</strong></p>
<p>If a customer wants to avail services of the Website and use it, registration is required. As a part of the registration, we collect basic information such as your name, gender, date of birth, email address, contact number, password, city, state, country, Credit Card information, other billing Information, etc.</p>
<p>Membership of this Website is available only to those above the age of 18, barring those “Incompetent to Contract” which <em>inter alia </em>include insolvents. If You are a minor and wish to use the Website, You may do so through Your legal guardian. The Company/Website reserves the right to terminate Your account on knowledge of You being a minor and having registered on the Website or availing any of its services.</p>
<p>Further, at any time during Your use of this Website, including but not limited to the time of registration, You are solely responsible for protecting the confidentiality of Your username and password, and any activity under the account shall be deemed to have been done by You. In the case that You provide Us with false and/or inaccurate details or we have reason to believe that You have done so, We hold the right to permanently suspend Your account.</p>
<p><strong>COMMUNICATIONS:</strong></p>
<p>By using this Website or Application, it is deemed that You have consented to receiving telephonic calls, SMSs and/or emails from Us at any time We deem fit. Such communications shall be sent to You on the telephone number and/or email address provided by You for the use of this Website or Application which are subject to our Privacy Policy. These communications include, but are not limited to contacting you through information received from Third Parties. Such communications by Us is for purposes that <em>inter alia </em>include clarification calls, marketing calls and promotional calls. In case You wish to stop receiving notifications from Us with regard to marketing and promotional calls/ with regard to any communication received from Us, You may do so by sending an email to info@joybynature.com.<br> In addition, You may also be contacted by Third Parties who may have access to the information disclosed by You or to whom We may have disclosed Your information for purposes such as, but not limited to, statistical compilations. <br> The sharing of the information provided by You shall be governed by our Privacy Policy at <a href="http://www.joybynature.com">www.joybynature.com</a></p>
<p><strong>ACCOUNT AND REGISTRATION OBLIGATIONS</strong></p>
<p>You must keep your account and registration details current and correct for communications related to your Use of the Website/App. By agreeing to the Terms of Use, the user agrees to receive promotional communication and newsletters from the Company and its partners. The user can opt out from such communication and/or newsletters either by unsubscribing on the Website itself, or by contacting the customer services team and placing a request for unsubscribing.</p>
<p><strong>CHARGES</strong></p>
<p>The usage of Website or downloading and installing of the Application is free of cost and this includes using the services of the App as well <br> However, We reserve the right to amend this no-fee policy and charge Users for downloading and installing the Application or the services provided. In the event of such change in policy, Users shall be intimated of the same via email/telephone and such change shall be effective as soon as Users have been intimated. Subsequent to such change, it is the choice of the User whether or not to continue with the services offered by Us.</p>
<p><strong>MODE OF PAYMENT</strong></p>
<p>The following payment options are available on the Website/App:</p>
<ol>
<li>Domestic and international credit cards issued by banks and financial institutions that are part of the Visa, Master Card &amp; Amex Card networks;</li>
<li>Visa &amp; Master Card Debit cards;</li>
<li>Netbanking/Direct Debit payments from select banks. <strong></strong>
</li>
</ol>
<h4>As prescribed by the financial institutions issuing the credit or debit cards affiliated with Visa / Master Card / Amex, the User will be required to submit his/her 16-digit card number, card expiry date and 3-digit CVV number (usually on the reverse of the card) while making an online transaction. The User must also have enrolled his/her card with VBV (Verified by Visa), MSC (MasterCard Secure Code) or any other applicable provider in order to complete the transaction. The User is hereby expressly made aware that his/her card statements will reflect that a payment has been made in favour of the Company.</h4>
<p><strong>REFUND</strong></p>
<p>All purchases made are final. Product once sold will not be exchanged/refunded except in circumstances like damage or spillage.</p>
<p><strong>USER’S OBLIGATIONS</strong></p>
<p>The User undertakes to fulfil the following obligations. Failure to satisfy any of these obligations gives Us the right to permanently suspend Your account and/or claim damages for any losses that accrue to Us or additional costs that may be imposed on us.</p>
<ol>
<ol>
<li>You hereby certify that you are at least 18 years of age.</li>
<li>You agree to ensure the email address provided in your account registration is valid at all times and shall keep your contact information accurate and up-to-date.</li>
<li>You agree to comply with all local laws and regulations governing the downloading, installation and/or use of the Application and Website, including, without limitation to, any usage rules set forth in this Agreement.</li>
<li>You undertake not to:</li>
</ol>
<li>Cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or software obtained from the Website or Application. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Website or Application is not permitted. Should You want to engage in one or more such actions, prior permission from Us must be obtained;</li>
<li>access (or attempt to access) the Website or Application and/or the materials or Services by any means other than through the interface that is provided by the Website or Application. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or Application or Content, or in any way reproduce or circumvent the navigational structure or presentation of the&nbsp; Website or Application, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website or Application is prohibited. You acknowledge and agree that by accessing or using the Application or Website Services, You may be exposed to content from other Users or Third Parties that You may consider offensive, indecent or otherwise objectionable. We disclaim all liabilities arising in relation to such offensive content on the Website or Application. Further, You may report such offensive content;</li>
<li>use the Website or Application in any manner that may impair, overburden, damage, disable or otherwise compromise (i) Company’s services; (ii) any other party's use and enjoyment of &nbsp;company’s services; or (iii) the services and products of any Third Party (including, without limitation to, the Authorized Device);</li>
<li>use the Services or Materials for any unlawful purposes or to conduct any unlawful activity, including, but not limited to, fraud, embezzlement, money laundering or identity theft;</li>
<li>abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others;</li>
<li>engage in any activity that interferes with or disrupts access to the Website or Application or the Services (or the servers and networks which are connected to the Application);upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website or Application or another's mobile phone;</li>
<li>download any file posted on the Website or the Application that you know, or reasonably should know, cannot be legally distributed in such manner;</li>
<li>probe, scan or test the vulnerability of the Website or Application or any connected network , nor breach the security or authentication measures on the Website or Application. You may not reverse look-up, trace or seek to trace any information on any other user, of or visitor to, the Website or Application, or exploit the Application or Service or information made available or offered by or through the Website or Application, in any way whether or not the purpose is to reveal any information, including but not limited to personal identification information, other than Your own information, as provided for by the Application;</li>
<li>disrupt or interfere with the security of, or otherwise cause harm to, the Website or Application, systems resources, servers or networks connected to or accessible through the Application or any affiliated or linked applications;</li>
<li>use the Website or Application or any material or Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or Application or other Third Parties;</li>
<li>violate any applicable laws or regulations for the time being in force within or outside your home country;</li>
<li>&nbsp;violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;</li>
<li>threaten the unity, integrity, defence, security or sovereignty of your home country, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation;</li>
<li>disseminate information through the Website or Application that is false, inaccurate or misleading, or violate any applicable laws or regulations for the time being in force in or outside your home country.</li>
</ol>
<p><strong>UPDATES ON APPLICATION</strong></p>
<p>From time to time, the Application may automatically check the version of the Application installed on the Authorized Device and, if applicable, provide updates for the Application (hereinafter referred to as “Updates”). Updates may contain, without limitation to, bug fixes, patches, enhanced functionality, plug-ins and new versions of the Application. By installing the Application, You authorize the automatic download and installation of Updates and agree to download and install Updates manually if necessary. Your use of the Application and Updates shall be governed by this Agreement (as amended by any terms and conditions that may be provided with Updates).</p>
<p><strong>ACTIONS UNDERTAKEN BY THE APPLICATION ON YOUR DEVICE:</strong></p>
<p>Upon download and installation of the Application, You grant the following permissions to the Application on the device You have installed the Application in.</p>
<ol>
<li>To read from, write on, modify and delete data pertaining to the Application on the device’s hard disk and/or external storage;</li>
<li>To access information about networks, access networks including Wi-Fi networks, receive and send data through the network;</li>
<li>To determine Your approximate location from sources like, but not limited to mobile towers and connected Wi-Fi networks;</li>
<li>To determine Your exact location from sources such as, but not limited to GPS;</li>
<li>To access the model number, IMEI number and details about the operating system of the device the Application has been installed on, as well as the phone number of the device;</li>
<li>To retrieve information about other application running on the device the Application has been installed on and open them;</li>
<li>To detect when the phone had been switched off and switched on for the purpose of sending notification/ push notifications;</li>
<li>To access and change the display and sound settings of the device the Application has been installed in.</li>
</ol>
<p><strong>COPYRIGHT</strong></p>
<ol>
<li>All information, content, services and software displayed on, transmitted through, or used in connection with the Website or Application, including for example news articles, reviews, directories, guides, text, photographs, images, illustrations, audio clips, video, html, source and object code, trademarks, logos, and the like (collectively and hereinafter referred to as the "Content"), as well as its selection and arrangement, is owned by Us. You may use the Content only through the Website or Application, and solely for your personal, non-commercial use.<strong></strong>
</li>
<li>You may not, republish any portion of the Content on any Internet, Intranet or extranet site or incorporate the Content in any database, compilation, archive or cache. You may not distribute any Content to others, whether or not for payment or other consideration, and you may not modify, copy, frame, cache, reproduce, sell, publish, transmit, display or otherwise use any portion of the Content. You may not scrape or otherwise copy our Content without permission. You agree not to decompile, reverse engineer or disassemble any software or other products or processes accessible through the Website or Application, not to insert any code or product or manipulate the content of the Application in any way that affects the user's experience, and not to use any data mining, data gathering or extraction method.<strong></strong>
</li>
</ol>
<p><strong>COPYRIGHT COMPLAINTS</strong></p>
<ol>
<ol>
<li>We respect the intellectual property of others. If You believe Your work has been copied in a way that constitutes copyright infringement or are aware of any infringing material on the Website or Application, please contact Us at info@joybynature.com.</li>
<li>Information and Content provided by the User by providing information to, communicating with, and/or placing material on, the Website or Application, including for example but not limited to, communication during any registration, You represent and warrant: <strong></strong>
</li>
</ol>
</ol>
<ol>
<li>You own or otherwise have all necessary rights to the content you provide and the rights to use it as provided in this Terms of Service;</li>
<li>all information You provide is true, accurate, current and complete, and does not violate these Terms of Service; and</li>
<li>the information and Content shall not cause injury to any person or entity. Using a name other than your own legal name is prohibited.</li>
</ol>
<p>For all such information and material, you grant us, a royalty-free, perpetual, irrevocable, non-exclusive right and license to use, copy, modify, display, archive, store, distribute, reproduce and create derivative works from such information, in any form, media, software or technology of any kind now existing or developed in the future. Without limiting the generality of the previous sentence, you authorize us to share the information across all our affiliated Websites or Applications, to include the information in a searchable format accessible by users of the Website or Application, and to use your name and any other information in connection with its use of the material you provide. You also grant the right to use any material, information, ideas, concepts, know-how or techniques contained in any communication you send to us for any purpose whatsoever, including but not limited to developing, manufacturing and marketing products using such information. All rights in this paragraph are granted without the need for additional compensation of any sort to you.</p>
<p><strong>GEOGRAPHICAL EXTENT </strong><br> The Application can be used in India. We make no representation that materials or Content available through our Application is appropriate or available for use outside any of the above countries.</p>
<ol>
<ol>
<li>If You access or use the Application from a country or location apart from those specified above, You are solely responsible for compliance with necessary laws and regulations for use of the Application. <strong></strong>
</li>
</ol>
</ol>
<p><strong>AMENDMENT</strong><br> We may modify, replace, refuse access to, suspend or discontinue the Services, partially or entirely, or add, change and modify prices for all or part of the Services for You or for all Users at any time and in Our sole discretion. These changes shall become effective upon providing a notice of the same to You via email/ the home screen of the website/Application. We further reserve the right to withhold, remove and or discard any content available as part of Your account, with or without notice, if deemed by Us to be contrary to this Agreement.</p>
<ol>
<ol>
<li>The Application has no obligation to provide You with a copy of the information You or any other User provides on the Application or that the Application has accessed.</li>
<li>Further, We reserve the right, in Our sole discretion, to modify or replace any part of this Agreement at any time, effective upon the date of giving Users notice of the same. Notice shall be provided of such change via email to the Users and/ or by posting a notice on the home screen of the Application.</li>
</ol>
</ol>
<p>You and We both understand that there may be instances of difficulty in accessing or receiving email communication. We are not responsible if any email notice gets caught by Your SPAM folder, or if You do not see the email, or if You have given us an incorrect email id or if for any other reason You do not receive the email notice. Therefore, we encourage you to frequently open the Application to monitor any changes. Your continued use of or access to the Services following the posting of any changes to this Agreement constitutes acceptance of those changes. We may also, in the future, offer new services and/ or features through the Application. Such new features and/ or services shall be subject to the terms and conditions of this Agreement.</p>
<p><strong>INDEMNIFICATION</strong><br> You agree to indemnify, hold harmless, and defend Us from and against any and all liability, loss, claim, damages, expense, or costs (including but not limited to attorneys' fees), incurred by or made by Us in connection with any claim arising from or related to:</p>
<ol>
<ol>
<li>Your use or any Third Party’s use via Your account of the Service provided by the Application and its Content;</li>
<li>Your disclosure of information to any Third Party, either through the Application or otherwise. (Please refer to our Privacy Policy for more details in this regard);</li>
<li>Any breach or violation of this Agreement, including any amendment, or of any statute or regulation by You, or any Third Party through Your account.</li>
</ol>
</ol>
<p>You agree to fully cooperate in indemnifying Us at Your expense.&nbsp;You also agree not to reach a settlement with any party without Our consent.</p>
<p><strong>DISCLAIMER OF LIABILITY</strong><br> The Company will not be responsible for any damage suffered by users from use of the services on this system. This without limitation includes loss of revenue/data resulting from delays, pricing issues or service interruptions as may occur because of any act/ omission. This disclaimer of liability also applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortuous behavior, negligence, or under any other cause of action. <br> In particular, neither the Website Owner nor any shareholders/members of the Company shall be liable in any way to you or to any other person, firm or corporation whatsoever for any loss, liability, damage (whether direct or consequential), personal injury or expense of any nature whatsoever arising from any delays, inaccuracies, errors in, or omission of any products/services.</p>
<p>User reviews are provided for informational purpose only. User reviews reflect the individual reviewer's results and experiences only and are not verified or endorsed by the Company/ Website/ Application.</p>
<p>The website may contain information available in the public domain with sources specifically mentioned therein and the same is not attributable to us. Such information without limitation may contain pictures and background stories of celebrities who use natural and organic products. &nbsp;Any person who wishes to raise an issue with regards to the same can write to Us at info@joybynature.com. <br> Please note that the Website/App does not claim that its products are endorsed by such celebrities/persons.</p>
<p><strong>DISPUTES ARISING OUT OF THIS AGREEMENT</strong><br> All disputes involving but not limited to rights conferred, compensation, refunds, and other claims will be resolved through a two-step Alternate Dispute Resolution mechanism.</p>
<ol>
<ol>
<li>
<strong>Stage 1: Mediation</strong>. In case of a dispute, the matter will first be attempted to be resolved by a sole mediator who is a neutral third party and will be selected at the mutual acceptance of a proposed mediator by both parties. Both parties may raise a name for the sole mediator and in the case both parties accept the proposed name, the said person shall be appointed as sole mediator. In case the parties are not able to reach a consensus within two proposed mediators, the Company reserves the right to decide the final mediator. The decision of the mediator is binding on both parties.</li>
<li>
<strong>Stage 2: Arbitration</strong>. In case that mediation does not yield a suitable result or preferred by any one of the parties, arbitration may follow, the award of which is binding on both parties. The Arbitration Board shall comprise three members – one appointed by each party and the third member to be nominated by the two appointed members by mutual consent. Arbitration shall be held at New Delhi, India. The proceedings of arbitration shall be in the English language. The arbitrator’s award shall be final and binding on the Parties.</li>
</ol>
</ol>
<p>The formation, interpretation and performance of this Agreement and any disputes arising out of it shall be governed by the law, rules and regulations of New Delhi, India. The exclusive jurisdiction and venue for actions and disputes may be as mentioned above, and You hereby submit to the jurisdiction of such courts.</p>
<p><strong>PRIVACY</strong><br> We encourage you to read the&nbsp;Privacy Policy, and to use the information it contains to make informed decisions regarding Your personal information. Please also note that certain information, statements, data and content which You provide on the Website/Application are likely to reveal Your information about You.&nbsp;You acknowledge and agree that your submission of such information is voluntary on Your part.&nbsp;Further, You acknowledge, consent and agree that we may access, preserve, and disclose information You provide to Us at any stage during Your use of the Application. Disclosures of information to Third Parties are further addressed in Our&nbsp;Privacy Policy. The data collected from the Users as well as from the Service provider may be located in servers outside of India.</p>
<p><strong>MISCELLANEOUS PROVISIONS:</strong></p>
<ol>
<ol>
<li>
<strong><em>Entire Agreement: </em></strong>This Agreement is the complete and exclusive statement of the agreements between You and Us with respect to the subject matter hereof and supersedes all other communications or representations or agreements (whether oral, written or otherwise) relating thereto.<strong></strong>
</li>
<li>
<strong><em>Waiver: </em></strong>The failure of either party at any time to require performance of any provision of this Agreement in no manner shall affect such party's right at a later time to enforce the same. No waiver by either party of any breach of this Agreement, whether by conduct or otherwise, in any one or more instances, shall be deemed to be, or construed as, a further or continuing waiver of any other such breach, or a waiver of any other breach of this Agreement.</li>
<li>
<strong><em>Severability: </em></strong>If any provision of this Agreement shall to any extent be held invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions of this Agreement shall in no way be affected or impaired thereby and each such provision of this Agreement shall be valid and enforceable to the fullest extent permitted by law. In such case, this Agreement shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the rights and commercial expectations of the parties hereto, as expressed herein.</li>
</ol>
</ol>
<p>&nbsp;</p>
</div>
  </main>
</body>
</html>`
	output := map[string]interface{}{"code": util.CODE_USR1001, "message": "Success", "result": termservice}
	htmloutput, err := json.Marshal(output)
	if err != nil {
		fmt.Println("privacy " + err.Error())
	}
	//c.JSON(iris.StatusOK, validationResp)
	c.Write(string(htmloutput))

}

func PrivacyAndPolicy(c *iris.Context) {
	//c.MustRender("privacy&policy.html", nil)
	policy := `<html>
<head>
</head>
<body>
<main class="main-content container" role="main">
<div class="rte">
  <p><strong>GENERAL</strong></p>
<ol>
<li>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
<li>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.joybynature.com as well as for the IOS/Android Application “Joybynature”.</li>
<li>The domain name: www.joybynature.com (which shall hereinafter be referred to as "Website") and the IOS/Android Application “Joybynature”, are owned and operated by Pavitra Retail Pvt. Ltd. (“<strong>Company</strong>”) a Private Company limited by shares, incorporated under the provisions of the Companies Act, and having its registered office at 43 Katwaria Sarai, New Delhi - 110016 , India where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.</li>
<li>For the purpose of this Privacy Policy (“<strong>Policy</strong>”), wherever the context so requires,
<ol>
<li>The term<strong> ‘You’ &amp;</strong> <strong>‘User’</strong> shall mean any legal person or entity accessing or using the services provided on this Website/Application, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872;</li>
<li>The terms <strong>‘We’</strong>,<strong> ‘Us’</strong> &amp;<strong> ‘Our’</strong> shall mean the Website /Application and/or the Company, as the context so requires<strong>.</strong>
</li>
<li>
<strong>The terms ‘Party’ &amp; ‘Parties’ shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires. </strong><strong> </strong>
</li>
</ol>
</li>
<li><strong>The headings of each section in this Policy are only for the purpose of organizing the various provisions under this Policy in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.</strong></li>
<li>The use of the Website /Application by the User is solely governed by this Policy as well as the Terms of Use of the Website<strong><em>/</em></strong>Application (“<strong>Terms</strong>”), available at www.joybynature.com, and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website /Application and/or using any of the services provided on the Website/Application shall be deemed to signify the User’s unequivocal acceptance of this Policy and the aforementioned Terms, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other.</li>
<li>The User unequivocally agrees that this Policy and the aforementioned Terms constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website/Application, and that the same shall be deemed to be incorporated into the Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User’s act of visiting any part of the Website/Application constitutes the User’s full and final acceptance of the Policy and the aforementioned Terms.</li>
<li>The Parties expressly agree that the Company retains the sole and exclusive right to amend or modify the Policy and the aforementioned Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the Policy and Terms, and stay updated on their provisions and requirements. If the User continues to use the Website/Application following such a change, the User will be deemed to have consented to any and all amendments/modifications made to the Policy and Terms. In so far as the User complies with the Policy and Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter, access and use the Website/Application.</li>
</ol>
<p><strong>COLLECTION OF PERSONAL AND OTHER INFORMATION</strong></p>
<ol>
<li>The User expressly agrees and acknowledges that the Company collects and stores the User’s personal information, which is provided by the User from time to time on the Website/Application, including but not limited to the User’s Name, date of birth, sex, address, user name, passwords, email address, shopping preferences, browsing history, etc., as well as any images or other information uploaded/published by the User on the Website/Application. The User is aware that this information will be used by the Company/Website/Application to provide services and features targeted at the User, that are most likely to meet the User’s needs, and also to customize and improve the Website/Application to make its users’ experiences safer and easier.</li>
<li>The User is aware that the Company/Website/Application may automatically track certain information about the User based upon the User’s IP address and the User’s behaviour on the Website/Application, and the User expressly consents to the same. The User is aware that this information is used to do internal research on user demographics, interests, and behaviour, to enable the Company/Website/Application to better understand, and cater to the interests of its users. The User is expressly made aware that such information may include the URL that the User visited prior to accessing the Website/Application, the URL which the User subsequently visits (whether or not these URLs form a part of the Website/Application), the User’s computer &amp; web browser information, the User’s IP address, etc.</li>
<li>If the User chooses to purchase services from the Website/Application, the User consents to allowing the Company/Website/Application to collect information about the User’s buying behaviour and trends.</li>
<li>If the User chooses to post messages / reviews / feedback anywhere on the Website/Application, including but not limited to message boards, chat rooms, other message areas, etc., the User is aware that any and all such information provided / uploaded will be collected and stored by the Company indefinitely, and that such retained information may be used to resolve disputes, provide customer support, troubleshoot problems, etc., and that such information, if requested,&nbsp; may be provided to judicial or governmental authorities of requisite jurisdiction, or otherwise used by the Company/Website/Application as permitted by applicable laws.</li>
<li>The User is aware that any and all information pertaining to the User collected by the Company, whether or not directly provided by the User to the Company/Website/Application, including but not limited to personal correspondence such as emails or letters, feedback from other users or third parties regarding the User’s activities or postings on the Website/Application, etc., may be collected and complied by the Company/Website/Application into a file/folder specifically created for / allotted to the User, and the User hereby expressly consents to the same.</li>
<li>The User is aware that while he/she can browse some sections of the Website/Application without being a registered user, certain activities require the User to provide valid personal information to the Company/Website/Application for the purpose of registration. The User is aware that the contact information provided to the Company/Website/Application may be used to send the User offers and promotions, whether or not based on the User’s previous orders and interests, and the User hereby expressly consents to receiving the same.</li>
<li>The User is aware that the Company/Website/Application may occasionally request the User to complete optional online surveys. These surveys may require the User to provide contact information and demographic information (like zip code, age, income bracket, sex, etc.). The User is aware that this data too is used to customise the Website/Application for the benefit of the User, and providing all users of the Website/Application with products/services/content that the Company/Website/Application believes they might be interested in availing of, and also to display content according to the User’s preferences.</li>
<li>The User is further aware that the Company/Website/Application may occasionally request the User to write reviews for products/services purchased/availed of by the User from the Website/Application. The User is aware that such reviews will help other users of the Website/Application make prudent and correct purchases and the User hereby expressly authorises the Company/Website/Application to publish any and all reviews written by the User on the Website/Application, along with the User’s name and certain contact details, for the benefit and use of other Users of the Website/Application.</li>
<li>Nothing contained herein shall be deemed to compel the Website/Application/Company to store, upload, publish, or display in any manner content/reviews/surveys/feedback submitted by the User, and the User hereby expressly authorises the Website/Application/Company to remove from the Website/Application any such content, review, survey, or feedback submitted by the User, without cause or being required to notify the User of the same.</li>
</ol>
<p><strong>COOKIES</strong></p>
<ol>
<li>The User is aware that a ‘Cookie’ is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular browser, and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User’s login identification, password, etc. The User is aware that the Website/Application places both permanent and temporary cookies in the User’s computer's hard drive &amp; Mobile Phone’s Memory Storage unit and web browser, and does hereby expressly consent to the same.</li>
<li>The User is further aware that the Website/Application uses data collection devices such as cookies on certain pages of the Website/Application to help analyse web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website/Application are only available through the use of such cookies. While the User is free to decline the Website/Application’s cookies if the User’s browser permits, the User may consequently be unable to use certain features on the Website/Application.</li>
<li>Additionally, the User is aware that he/she might encounter ‘cookies’ or other similar devices on certain pages of the Website/Application that are placed by third parties or affiliates of the Company/Website/Application. The User expressly agrees and acknowledges that the Company/Website/Application does not control the use of such cookies/other devices by third parties, that the Company/Website/Application is in no way responsible for the same, and that the User assumes any and all risks in this regard.</li>
</ol>
<p><strong>DIVULGING/SHARING OF PERSONAL INFORMATION</strong></p>
<ol>
<li>The User is aware that the Website/Application/Company may share the User’s personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website/Application’s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.</li>
<li>The User is aware that the Website/Application/Company may disclose personal information if required to do so by law or if the Website/Application/Company in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The Website/Application/Company may also disclose the User’s personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.</li>
<li>The User is further aware that the Website/Application/Company and its affiliates may share / sell some or all of the User’s personal information with other business entities should the Company/Website/Application (or its assets) plan to merge with, or be acquired by such business entity, or in the event of re-organization, amalgamation, or restructuring of the Company’s business. Such business entity or new entity will continue to be bound by the Terms and Policy, as may be amended from time to time.</li>
<li>The User is further aware that the Website/Application/Company will share the user’s personal information with payment gateways in order to process the payments in a swift manner.<strong>&nbsp;</strong>
</li>
</ol>
<p><strong>SECURITY</strong><br> Transactions on the Website/Application are secure and protected. Any information entered by the User when transacting on the Website/Application is encrypted to protect the User against unintentional disclosure to third parties. The User’s credit and debit card information maybe received, stored by or retained by the Company / Website/Application for the purpose of providing a “Quick Checkout” facility to the User. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.<strong>&nbsp;</strong></p>
<p><strong>THIRD PARTY ADVERTISEMENTS / PROMOTIONS</strong><br> The User is aware that the Company/Website/Application uses third-party advertising companies to serve ads to the users of the Website/Application. The User is aware that these companies may use information relating to the User’s visits to the Website/Application and other Website/Applications in order to provide customised advertisements to the User. Furthermore, the Website/Application may contain links to other Website/Applications that may collect personally identifiable information about the User. The Company/Website/Application is not responsible for the privacy practices or the content of any of the aforementioned linked Website/Applications, and the User expressly acknowledges the same and agrees that any and all risks associated will be borne entirely by the User.</p>
<p><strong>USER’S CONSENT</strong><br> By using the Website/Application and/ or by providing information to the Company through the Website/Application, the User consents to the collection and use of the information disclosed by the User on the Website/Application in accordance with this Policy, including but not limited to the User’s consent the Company/Website/Application sharing/divulging the User’s information, as per the terms contained hereinabove in Section 4 of the Policy.</p>
<p><strong>GRIEVANCE OFFICER</strong><br> In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:</p>
<p>Name: <br> Contact info.: <strong></strong><strong>&nbsp;</strong></p>
<p><strong>DISPUTE RESOLUTION AND JURISDICTION</strong><br> It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of this Policy and any disputes arising herefrom will be resolved through a two-step Alternate Dispute Resolution (“<strong>ADR</strong>”) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Policy and/or Terms.</p>
<ol>
<li>
<strong>Mediation</strong>: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed hereinbelow;</li>
<li>
<strong>Arbitration</strong>. In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of New Delhi, India.</li>
</ol>
<p>The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at the city of New Delhi, India shall have exclusive jurisdiction over any disputes arising between the Parties.</p>
</div>
  <main class="main-content container" role="main">
</body>
</html>`

	//fmt.Println(terms)
	output := map[string]interface{}{"code": util.CODE_USR1001, "message": "Success", "result": policy}
	htmloutput, err := json.Marshal(output)
	if err != nil {
		fmt.Println("privacy " + err.Error())
	}
	//c.JSON(iris.StatusOK, validationResp)
	c.Write(string(htmloutput))
}

func Support(c *iris.Context) {
	support := `<html><header class="page-header">
</header><div class="rte">
 Call us now at 011-39595895 or Email us at info@joybynature.com
</div></html>`

	output := map[string]interface{}{"code": util.CODE_USR1001, "message": "Success", "result": support}
	htmloutput, err := json.Marshal(output)
	if err != nil {
		fmt.Println("Support Data Issue" + err.Error())
	}
	//c.JSON(iris.StatusOK, validationResp)
	c.Write(string(htmloutput))
}
func Release(c *iris.Context) {
	release := `<html><p>App Version : v1.3.4</p>
<p><strong>Features Added:</strong><br />1) User Profile added<br />2) Upload User image enabled<br />3) User Follow option enabled<br /><br /><strong>Bugs Fixed:</strong><br />1) Multiple Login Issues fixed<br />2) Image issue fixed in story<br />3) Anonymous user bug fixed<br />4) Shop 'View All' bug fixed</p>
<p>=======================================</p>
<p>App Version : v1.0.0</p>
<p><strong>MAIN FEATURES:</strong></p>
<p><strong>Shop</strong></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">More than 5,000 products and 300 plus unique organic brands across all categories</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">A range of certified organic, natural, herbal and ayurvedic product available</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Easy navigation and enhanced product search</span></li>
</ul>
<p><strong>Q&amp;A</strong></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Introducing brand new health community </span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Share ideas, home remedies, cure, exercise routine etc with other community members</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ask a question or answer wellbeing related questions</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Discover wellbeing and help the community get healthier</span></li>
</ul>
<p><strong>Stories</strong></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Real users share their transformation story</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Read to get motivated and start your own fitness regime today</span></li>
</ul>
<p> </p>
<p> </p></html>`

	output := map[string]interface{}{"code": util.CODE_USR1001, "message": "Success", "result": release}
	htmloutput, err := json.Marshal(output)
	if err != nil {
		fmt.Println("Support Data Issue" + err.Error())
	}
	//c.JSON(iris.StatusOK, validationResp)
	c.Write(string(htmloutput))
}

func AddQuestionTemplate(c *iris.Context){
		
//	c.ServeFile("addQA.html",false)
	iris.StaticWeb("/public","templates/hi.html", 1)
}